version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "4700:4700"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4700
        NEXT_PUBLIC_ZENTTO_API_URL: http://localhost:4000
    ports:
      - "3300:3300"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: zentto_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tickets123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped

volumes:
  pgdata:
